import type { Locale } from './i18n-config';
const labels = {
 core_listings:['إنشاء الإعلانات وإدارتها','Çêkirin û rêveberiya îlanan','Anzeigen erstellen und verwalten','Create and manage listings'],
 chat:['المراسلة مع المستخدمين','Peyam bi bikarhêneran re','Nachrichten mit Nutzern','Messaging with users'],
 higher_listing_limit:['عدد أكبر من الإعلانات','Îlanên zêdetir','Mehr Anzeigen','More listings'],
 unlimited_listings:['إعلانات بلا حد وفق السياسة','Îlan bê sînor','Unbegrenzte Anzeigen gemäß Richtlinie','Unlimited listings by policy'],
 basic_analytics:['إحصائيات المشاهدات والمفضلة','Statîstîkên dîtin û bijareyan','Aufruf- und Favoritenstatistik','Views and favorites analytics'],
 advanced_analytics:['إحصائيات متقدمة','Statîstîkên pêşketî','Erweiterte Statistiken','Advanced analytics'],
 priority_support:['دعم بأولوية','Piştgiriya pêşîn','Bevorzugter Support','Priority support'],
 account_manager:['مدير حساب مخصص','Rêveberê hesabê','Persönlicher Account-Manager','Dedicated account manager'],
 message_support:['دعم بالرسائل','Piştgirî bi peyam','Nachrichten-Support','Message support'],
 email_support:['دعم بالبريد','Piştgirî bi e-name','E-Mail-Support','Email support'],
 guide:['دليل الاستخدام PDF','Rêbera PDF','PDF-Anleitung','PDF user guide'],
 verified:['حساب موثّق','Hesabê pejirandî','Verifiziertes Konto','Verified account'],
 suspended:['حسابك موقوف. تواصل مع الدعم.','Hesabê te hatiye rawestandin. Bi piştgiriyê re têkilî dayne.','Dein Konto ist gesperrt. Kontaktiere den Support.','Your account is suspended. Contact support.'],
 avatar:['الصورة الشخصية','Wêneya profîlê','Profilbild','Profile photo'],
 imageLimit:['اختر صورة JPEG أو PNG أو WebP حتى 5 ميغابايت.','Wêneyeke JPEG, PNG an WebP heta 5 MB hilbijêre.','Wähle ein JPEG-, PNG- oder WebP-Bild bis 5 MB.','Choose a JPEG, PNG or WebP image up to 5 MB.'],
 latitude:['خط العرض للمكتب','Firehiya ofîsê','Breitengrad des Büros','Office latitude'],
 longitude:['خط الطول للمكتب','Dirêjahiya ofîsê','Längengrad des Büros','Office longitude'],
 metadataError:['تم حفظ الملف الشخصي، لكن تعذّر تحديث بيانات جلسة الدخول.','Profîl hat tomarkirin, lê daneyên têketinê nehatin nûkirin.','Profil gespeichert, aber die Anmeldedaten konnten nicht aktualisiert werden.','Profile saved, but sign-in metadata could not be updated.'],
 title:['حسابي','Hesabê min','Mein Konto','My account'],
 edit:['تعديل الملف الشخصي','Profîlê biguherîne','Profil bearbeiten','Edit profile'],
 saved:['عمليات البحث المحفوظة','Lêgerînên tomarkirî','Gespeicherte Suchen','Saved searches'],
 language:['اللغة','Ziman','Sprache','Language'],
 help:['معلومات ومساعدة','Agahî û alîkarî','Informationen und Hilfe','Information and help'],
 blocked:['المستخدمون المحظورون','Bikarhênerên astengkirî','Blockierte Nutzer','Blocked users'],
 privacy:['خصوصية الإعلانات','Nepeniya reklaman','Werbedatenschutz','Advertising privacy'],
 deletion:['حذف الحساب','Hesabê jê bibe','Konto löschen','Delete account'],
 notifications:['الإشعارات','Agahdarî','Benachrichtigungen','Notifications'],
 listings:['إعلاناتي','Îlanên min','Meine Anzeigen','My listings'],
 messages:['الرسائل','Peyam','Nachrichten','Messages'],
 favorites:['المفضلة','Bijare','Favoriten','Favorites'],
 admin:['لوحة الإدارة','Rêveberî','Verwaltung','Administration'],
 logout:['تسجيل الخروج','Derkeve','Abmelden','Sign out'],
 login:['تسجيل الدخول','Têketin','Anmelden','Sign in'],
 required:['سجّل الدخول لعرض حسابك.','Ji bo hesabê xwe têkeve.','Melde dich an, um dein Konto zu sehen.','Sign in to view your account.'],
 error:['تعذر تحميل البيانات. أعد المحاولة.','Dane nehatin barkirin. Dîsa biceribîne.','Daten konnten nicht geladen werden. Versuche es erneut.','Could not load data. Try again.'],
 retry:['إعادة المحاولة','Dîsa biceribîne','Erneut versuchen','Try again'],
 actionError:['لم يتم حفظ التغيير. أعد المحاولة.','Guhertin nehat tomarkirin. Dîsa biceribîne.','Änderung nicht gespeichert. Versuche es erneut.','Change was not saved. Try again.'],
 person:['شخص خاص','Kesane','Privatperson','Individual'],
 agency:['مكتب أو شركة','Ofîs an şirket','Büro oder Unternehmen','Office or company'],
 plan:['باقتك الحالية','Pakêta te','Dein aktuelles Paket','Your current plan'],
 details:['تفاصيل الباقة','Hûrgiliyên pakêtê','Paketdetails','Plan details'],
 analytics:['إحصائيات إعلاناتي','Statîstîkên îlanên min','Meine Anzeigenstatistik','My listing analytics'],
 expires:['صالحة حتى','Derbasdar heta','Gültig bis','Valid until'],
 empty:['لا توجد بيانات بعد.','Hêj dane tune ne.','Noch keine Daten.','No data yet.'],
 open:['فتح البحث','Lêgerînê veke','Suche öffnen','Open search'],
 alerts:['تنبيهات البحث','Agahdariyên lêgerînê','Suchbenachrichtigungen','Search alerts'],
 remove:['حذف','Jê bibe','Löschen','Delete'],
 confirm:['حذف هذا البحث المحفوظ؟','Vê lêgerînê jê bibî?','Diese gespeicherte Suche löschen?','Delete this saved search?'],
 unblock:['إلغاء الحظر','Astengê rake','Blockierung aufheben','Unblock'],
 confirmUnblock:['إلغاء حظر هذا المستخدم؟','Astenga vî bikarhênerî rake?','Blockierung dieses Nutzers aufheben?','Unblock this user?'],
 save:['حفظ البحث','Lêgerînê tomar bike','Suche speichern','Save search'],
 name:['اسم البحث','Navê lêgerînê','Name der Suche','Search name'],
 savedOk:['تم حفظ البحث.','Lêgerîn hat tomarkirin.','Suche gespeichert.','Search saved.'],
 unsupported:['هذه الفلاتر غير متوافقة بعد مع البحث المحفوظ المشترك مع التطبيق.','Ev parzûn hêj bi lêgerîna tomarkirî ya sepanê re ne lihevhatî ne.','Diese Filter werden von gemeinsamen gespeicherten Suchen noch nicht unterstützt.','These filters are not yet supported by saved searches shared with the app.'],
 views:['المشاهدات','Dîtin','Aufrufe','Views'],
 calls:['الاتصالات','Telefon','Anrufe','Calls'],
 shares:['المشاركات','Parvekirin','Geteilt','Shares'],
 support:['التواصل مع الدعم','Têkilî bi piştgiriyê','Support kontaktieren','Contact support'],
 howto:['كيفية الاستخدام','Çawa tê bikaranîn','So funktioniert es','How to use'],
 policy:['سياسة الخصوصية','Siyaseta nepeniyê','Datenschutzerklärung','Privacy policy'],
 terms:['شروط الاستخدام','Mercên bikaranînê','Nutzungsbedingungen','Terms of use'],
 safety:['قواعد السلامة','Rêbazên ewlehiyê','Sicherheitshinweise','Safety'],
 community:['قواعد المجتمع','Rêbazên civakê','Community-Regeln','Community rules'],
 about:['عن RojDeal','Derbarê RojDeal','Über RojDeal','About RojDeal'],
 noTracking:['يتضمن الموقع خدمة Google AdSense. راجع سياسة الخصوصية وخيارات الموافقة التي تعرضها Google عند توفرها في منطقتك.','Malper xizmeta Google AdSense dihewîne. Siyaseta nepeniyê û vebijarkên razîbûnê yên Google li herêma xwe binêre.','Die Website bindet Google AdSense ein. Beachte die Datenschutzerklärung und die von Google für deine Region angebotenen Einwilligungsoptionen.','The website includes Google AdSense. Review the privacy policy and the consent choices Google offers for your region.'],
} as const;
export type AccountLabel = keyof typeof labels;
export function accountText(lang: Locale, key: AccountLabel): string { return labels[key][['ar','ku','de','en'].indexOf(lang)]; }
