import type { Locale } from './i18n-config';
import { needsListingLogin } from './auth-return';
export const listingFeedback = {
 ar: { checking: 'جارٍ تحميل نموذج الإعلان…', retry: 'إعادة المحاولة', load: 'تعذر تحميل نموذج الإعلان. تحقق من الاتصال وحاول مجدداً.', session: 'جلسة الدخول غير متاحة. بياناتك باقية هنا؛ افتح تسجيل الدخول في تبويب آخر، ثم ارجع وحاول مجدداً.', login: 'تسجيل الدخول في تبويب آخر', owner: 'هذه البيانات تخص الحساب الذي فتح النموذج. ارجع إلى نفس الحساب لإكمالها.', permission: 'لم يُسمح بحفظ الإعلان. تحقق من صلاحيات حسابك أو تواصل مع الدعم. بياناتك محفوظة في هذا النموذج.', network: 'تعذر الاتصال. بياناتك باقية هنا؛ تحقق من الإنترنت وأعد المحاولة.', image: 'تحقق من الصور: الحد الأقصى 12 صورة، وبصيغة صورة صالحة.', video: 'تحقق من الفيديو: مدة لا تتجاوز 5 دقائق وحجم لا يتجاوز 48 MB.', location: 'اختر موقعاً صالحاً للإعلان.', saved: 'بيانات الإعلان محفوظة. صحح الخطأ وأعد المحاولة هنا دون إنشاء إعلان آخر. الصور التي اكتمل رفعها تبقى مرفقة.', failed: 'تعذر إكمال الحفظ أو النشر. بياناتك باقية هنا؛ أعد المحاولة أو تواصل مع الدعم.' },
 ku: { checking: 'Forma îlanê tê barkirin…', retry: 'Dîsa biceribîne', load: 'Forma îlanê nehat barkirin. Girêdanê kontrol bike û dîsa biceribîne.', session: 'Danişîna têketinê tune ye. Agahî li vir dimînin; di tabloyeke din de têkeve, paşê vegere û dîsa biceribîne.', login: 'Di tabloyeke din de têkeve', owner: 'Ev agahî yên hesabê ku form vekir in. Bi heman hesabê vegere.', permission: 'Tomarkirina îlanê nehat destûr kirin. Mafên hesabê kontrol bike an bi piştgiriyê re biaxive.', network: 'Girêdan bi ser neket. Agahî li vir dimînin; înternetê kontrol bike û dîsa biceribîne.', image: 'Wêneyan kontrol bike: herî zêde 12 wêne bi formateke derbasdar.', video: 'Vîdyoyê kontrol bike: herî zêde 5 deqe û 48 MB.', location: 'Cihekî derbasdar hilbijêre.', saved: 'Daneyên îlanê hatin tomarkirin. Xeletiyê rast bike û li vir dîsa biweşîne; îlan du caran nayê çêkirin. Wêneyên barkirî dimînin.', failed: 'Tomarkirin an weşandin bi ser neket. Agahî li vir dimînin; dîsa biceribîne an bi piştgiriyê re biaxive.' },
 de: { checking: 'Anzeigeformular wird geladen…', retry: 'Erneut versuchen', load: 'Das Anzeigeformular konnte nicht geladen werden. Verbindung prüfen und erneut versuchen.', session: 'Die Anmeldung ist nicht verfügbar. Deine Eingaben bleiben hier erhalten. Melde dich in einem anderen Tab an und kehre zum erneuten Versuch zurück.', login: 'In einem anderen Tab anmelden', owner: 'Diese Eingaben gehören zum Konto, das das Formular geöffnet hat. Kehre zu diesem Konto zurück.', permission: 'Das Speichern wurde nicht erlaubt. Prüfe deine Kontoberechtigungen oder kontaktiere den Support. Deine Eingaben bleiben im Formular.', network: 'Verbindung fehlgeschlagen. Deine Eingaben bleiben erhalten. Prüfe das Internet und versuche es erneut.', image: 'Bilder prüfen: maximal 12 Bilder in einem gültigen Bildformat.', video: 'Video prüfen: maximal 5 Minuten und 48 MB.', location: 'Wähle einen gültigen Anzeigenstandort.', saved: 'Anzeigendaten gespeichert. Korrigiere den Fehler und veröffentliche hier erneut, ohne eine doppelte Anzeige anzulegen. Bereits hochgeladene Bilder bleiben angehängt.', failed: 'Speichern oder Veröffentlichen fehlgeschlagen. Deine Eingaben bleiben erhalten. Versuche es erneut oder kontaktiere den Support.' },
 en: { checking: 'Loading listing form…', retry: 'Try again', load: 'Could not load the listing form. Check your connection and retry.', session: 'Your sign-in session is unavailable. Your entries remain here. Sign in in another tab, then return and retry.', login: 'Sign in in another tab', owner: 'These entries belong to the account that opened the form. Return to that account to continue.', permission: 'Saving was not allowed. Check your account permissions or contact support. Your entries remain in the form.', network: 'Connection failed. Your entries remain here. Check your internet connection and retry.', image: 'Check your images: at most 12 files in a valid image format.', video: 'Check your video: at most 5 minutes and 48 MB.', location: 'Choose a valid listing location.', saved: 'Listing data saved. Correct the error and publish again here without creating a duplicate listing. Images already uploaded remain attached.', failed: 'Could not finish saving or publishing. Your entries remain here. Retry or contact support.' },
} as const;
export function listingError(error: unknown, lang: Locale): string {
 const text = listingFeedback[lang];
 const e = (error && typeof error === 'object' ? error : {}) as {message?: string;code?: string;status?: number;statusCode?: string;name?: string};
 if (needsListingLogin(error)) return text.session;
 if (e.message === 'draft_owner_changed') return text.owner;
 if (e.code === '42501' || Number(e.status ?? e.statusCode) === 403) return text.permission;
 if (['image_limit', 'image_required', 'invalid_image'].includes(e.message ?? '')) return text.image;
 if (e.message === 'invalid_video') return text.video;
 if (e.message === 'location_required') return text.location;
 if (e.name === 'AuthRetryableFetchError' || /failed to fetch|fetch failed|network|load failed/i.test(e.message ?? '')) return text.network;
 return text.failed;
}
