const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
function fixture({owner='me',kind='image',deny=false,lost=false}={}){
 const rows={listings:[{id:'listing',owner_id:owner}],listing_media:[{id:'media',listing_id:'listing',owner_id:owner,kind,storage_path:`${owner}/listing/file`,sort_order:0}]},calls=[];
 const supabase={auth:{getUser:async()=>({data:{user:{id:'me'}},error:null})},from(table){let filters=[],remove=false,single=false;const q={select(){return q},eq(k,v){filters.push([k,v]);return q},order(){return q},maybeSingle(){single=true;return q},delete(){remove=true;return q},then(ok,bad){return Promise.resolve().then(()=>{calls.push([table,remove?'delete':'select',filters]);const found=rows[table].filter(r=>filters.every(([k,v])=>r[k]===v));if(remove){if(deny)return {data:null,error:{code:'42501'}};rows[table]=rows[table].filter(r=>!found.includes(r));if(lost)return {data:null,error:new Error('network')};}return {data:single?found[0]??null:found,error:null};}).then(ok,bad)}};return q},rpc:async(name,args)=>{calls.push(['rpc',name,args]);if(deny)return {error:{code:'42501'}};rows.listing_media=[];return {error:null}},storage:{from:bucket=>({getPublicUrl:path=>({data:{publicUrl:`https://example.invalid/${bucket}/${path}`}}),remove:async paths=>{calls.push(['storage',bucket,paths]);return {error:null}}})}};
 const source=ts.transpileModule(fs.readFileSync('src/services/listing-media.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,m={exports:{}};new Function('module','exports','require',source)(m,m.exports,n=>n==='@/lib/supabase'?{supabase}:require(n));return {api:m.exports,rows,calls};
}
test('existing media requires listing ownership even when an account could have staff permissions',async()=>{const f=fixture({owner:'other'});await assert.rejects(f.api.ownListingMedia('listing'),/listing_owner_required/);await assert.rejects(f.api.removeOwnListingMedia('listing','media'),/listing_owner_required/);assert.equal(f.calls.some(c=>c[0]==='storage'||c[0]==='rpc'||c[1]==='delete'),false);});
test('image removal deletes its owner-scoped database reference before storage and preserves storage on denial',async()=>{const f=fixture();await f.api.removeOwnListingMedia('listing','media');assert.equal(f.rows.listing_media.length,0);const deleted=f.calls.findIndex(c=>c[1]==='delete'),storage=f.calls.findIndex(c=>c[0]==='storage');assert.ok(deleted<storage);assert.deepEqual(f.calls[deleted][2],[['id','media'],['listing_id','listing'],['owner_id','me']]);const denied=fixture({deny:true});await assert.rejects(denied.api.removeOwnListingMedia('listing','media'));assert.equal(denied.calls.some(c=>c[0]==='storage'),false);});
test('video deletion delegates to the existing ownership-checked atomic replacement RPC',async()=>{const f=fixture({kind:'video'});await f.api.removeOwnListingMedia('listing','media');assert.equal(f.calls.find(c=>c[0]==='rpc')[1],'replace_own_listing_video');assert.equal(f.calls.find(c=>c[0]==='rpc')[2].new_storage_path,null);assert.equal(f.calls.some(c=>c[0]==='listing_media'&&c[1]==='delete'),false);});
