'use client';
import {useEffect,useState} from 'react';
import {legalDocuments,saveLegalDocument,documentTypes,type LegalDocument} from '@/services/legal-documents';
import {legalTitles} from '@/components/legal/SharedLegalDocuments';
import {AccountState} from '@/components/account/AccountState';
import {accountText} from '@/lib/account-copy';
import type {Locale} from '@/lib/i18n-config';
const labels={ar:{edit:'تعديل',add:'مستند جديد',version:'الإصدار',title:'العنوان',content:'المحتوى',url:'الرابط',date:'بدء السريان',active:'تفعيل هذا الإصدار',accept:'يتطلب موافقة المستخدم',save:'حفظ',cancel:'إلغاء',confirm:'حفظ المستند المشترك؟ تفعيله يستبدل الإصدار النشط لنفس النوع واللغة في التطبيق والموقع.',saved:'تم حفظ المستند.',type:'نوع المستند'},ku:{edit:'Biguherîne',add:'Belgeya nû',version:'Guherto',title:'Sernav',content:'Naverok',url:'Girêdan',date:'Dema destpêkê',active:'Vê guhertoyê çalak bike',accept:'Razîbûna bikarhêner pêwîst e',save:'Tomar bike',cancel:'Betal',confirm:'Belgeya hevpar tomar bikî? Çalakkirin guhertoya çalak a heman cure û zimanî diguherîne.',saved:'Belge hat tomarkirin.',type:'Cure'},de:{edit:'Bearbeiten',add:'Neues Dokument',version:'Version',title:'Titel',content:'Inhalt',url:'Link',date:'Gültig ab',active:'Diese Version aktivieren',accept:'Zustimmung erforderlich',save:'Speichern',cancel:'Abbrechen',confirm:'Gemeinsames Dokument speichern? Aktivierung ersetzt die aktive Version dieses Typs und dieser Sprache in App und Website.',saved:'Dokument gespeichert.',type:'Dokumenttyp'},en:{edit:'Edit',add:'New document',version:'Version',title:'Title',content:'Content',url:'Link',date:'Effective from',active:'Activate this version',accept:'Requires acceptance',save:'Save',cancel:'Cancel',confirm:'Save the shared document? Activating replaces the active version of this type and language in the app and website.',saved:'Document saved.',type:'Document type'}};
const types:Record<string,string[]>={privacy:['الخصوصية','Nepenî','Datenschutz','Privacy'],terms:['الشروط','Merc','Nutzungsbedingungen','Terms'],community_rules:['قواعد المجتمع','Rêbazên civakê','Community-Regeln','Community rules'],account_deletion:['حذف الحساب','Jêbirina hesabê','Kontolöschung','Account deletion'],impressum:['بيانات الناشر','Weşanger','Impressum','Legal notice'],payment_terms:['شروط الدفع','Mercên pere','Zahlungsbedingungen','Payment terms'],cookie_policy:['ملفات الارتباط','Çerez','Cookie-Richtlinie','Cookie policy'],ad_privacy:['خصوصية الإعلانات','Nepeniya reklaman','Werbedatenschutz','Advertising privacy']};
export function AdminSharedLegal({lang}:{lang:Locale}){
 const t=labels[lang],[rows,setRows]=useState<LegalDocument[]>([]),[loading,setLoading]=useState(true),[failed,setFailed]=useState(false),[version,setVersion]=useState(0),[form,setForm]=useState<LegalDocument|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{let live=true;setLoading(true);setFailed(false);void legalDocuments().then(r=>{if(live)setRows(r);}).catch(()=>{if(live)setFailed(true);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[version]);
 const field='w-full rounded-xl border p-3';
 if(loading||failed)return <AccountState lang={lang} loading={loading} error={failed} retry={()=>setVersion(v=>v+1)}/>;
 return <section className="space-y-4 rounded-3xl bg-white p-5"><h2 className="text-xl font-black">{legalTitles[lang]}</h2>{notice&&<p role="status">{notice}</p>}{form?<form className="space-y-3" onSubmit={async e=>{e.preventDefault();if(busy||!window.confirm(t.confirm))return;setBusy(true);setNotice('');try{const id=await saveLegalDocument(form);setRows(r=>[{...form,id},...r.filter(x=>x.id!==id)]);setForm(null);setNotice(t.saved);setVersion(v=>v+1);}catch{setNotice(accountText(lang,'actionError'));}finally{setBusy(false);}}}><fieldset disabled={busy} className="space-y-3"><label className="block">{t.type}<select className={field} value={form.document_type} onChange={e=>setForm({...form,document_type:e.target.value as LegalDocument['document_type']})}>{documentTypes.map(type=><option key={type} value={type}>{types[type][['ar','ku','de','en'].indexOf(lang)]}</option>)}</select></label><label className="block">{accountText(lang,'language')}<select className={field} value={form.language} onChange={e=>setForm({...form,language:e.target.value as Locale})}>{['ar','ku','de','en'].map(l=><option key={l}>{l}</option>)}</select></label>{(['version','title','public_url','effective_at']as const).map(k=><label className="block" key={k}>{k==='public_url'?t.url:k==='effective_at'?t.date:t[k]}<input required={k!=='public_url'} type={k==='public_url'?'url':'text'} className={field} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label className="block">{t.content}<textarea rows={10} className={field} dir={form.language==='ar'?'rtl':'ltr'} value={form.content} onChange={e=>setForm({...form,content:e.target.value})}/></label><label className="flex gap-2"><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/>{t.active}</label><label className="flex gap-2"><input type="checkbox" checked={form.requires_acceptance} onChange={e=>setForm({...form,requires_acceptance:e.target.checked})}/>{t.accept}</label><div className="flex gap-3"><button className="rounded-xl bg-rojRed px-4 py-3 font-bold text-white">{t.save}</button><button type="button" onClick={()=>setForm(null)}>{t.cancel}</button></div></fieldset></form>:<><button className="rounded-xl border p-3 font-bold" onClick={()=>setForm({document_type:'privacy',version:'',language:lang,title:'',content:'',public_url:'',effective_at:new Date().toISOString(),is_active:false,requires_acceptance:false})}>{t.add}</button><div className="grid gap-3 md:grid-cols-2">{rows.map(row=><article key={row.id} className="space-y-2 rounded-xl border p-3"><h3 className="break-words font-bold">{row.title}</h3><p className="text-sm">{row.language} · {row.version} · {row.is_active?'✓':'—'}</p><button className="text-rojRed" onClick={()=>{setForm({...row});setNotice('');}}>{t.edit}</button></article>)}</div></>}</section>;
}
