'use client';
import {useEffect,useState} from 'react';
import {assignScopedStaff,staffRoles,type AdminRow} from '@/services/admin-operations';
import {markets,type Market} from '@/services/markets';
import {activeLocations,type ActiveLocation} from '@/services/locations';
import {locationPath} from '@/lib/location-path';
import {supabase} from '@/lib/supabase';
import type {Locale} from '@/lib/i18n-config';
const copy:Record<string,string[]>={title:['إضافة تعيين إداري محدود','Tayînkirina rêveberî ya sînorkirî','Begrenzte Verwaltungsrolle hinzufügen','Add a scoped staff assignment'],note:['هذا التعيين يضاف إلى الصلاحيات الحالية ولا يستبدلها. لتقييد موظف لديه صلاحيات أوسع، راجع وأزل التعيينات القديمة أولاً من قائمة الفريق.','Ev tayînkirin li destûrên heyî zêde dibe; wan naguherîne. Ji bo sînorkirinê, tayînkirinên kevn berê ji lîsteya tîmê rake.','Die Zuweisung ergänzt bestehende Rechte. Um weitergehende Rechte einzuschränken, zuerst alte Zuweisungen in der Teamliste prüfen und entfernen.','This adds to existing permissions; it does not replace them. To restrict broader access, first review and remove old assignments in the team list.'],email:['البريد الإلكتروني للحساب','E-nameya hesabê','Konto-E-Mail','Account email'],role:['الدور','Rol','Rolle','Role'],market:['الدولة / السوق','Welat / bazar','Land / Markt','Country / market'],location:['معرّف الموقع (اختياري)','ID ya cihê (bijartî)','Standort-ID (optional)','Location ID (optional)'],category:['القسم','Beş','Kategorie','Category'],expiry:['تاريخ انتهاء اختياري','Dema dawiyê (bijartî)','Ablaufzeit (optional)','Expiry (optional)'],reason:['ملاحظة التعيين','Têbîniya tayînkirinê','Zuweisungsnotiz','Assignment note'],any:['غير مقيّد بهذا الحقل','Di vê qadê de bê sînor','In diesem Feld unbeschränkt','Unrestricted in this field'],save:['إضافة التعيين','Tayînkirinê zêde bike','Zuweisung hinzufügen','Add assignment'],confirm:['إضافة هذا التعيين دون حذف صلاحيات سابقة؟','Vê tayînkirinê bê jêbirina destûrên kevn zêde bikî?','Zuweisung hinzufügen, ohne bisherige Rechte zu entfernen?','Add this assignment without removing existing permissions?'],saved:['تمت إضافة التعيين. حدّث قائمة الفريق لعرضه.','Tayînkirin hat zêdekirin. Lîsteya tîmê nû bike.','Zuweisung hinzugefügt. Teamliste aktualisieren.','Assignment added. Refresh the team list.'],error:['تعذر تحميل الخيارات أو إضافة التعيين. تحقق من الحساب والصلاحية والنطاق المحدد.','Vebijark an tayînkirin bi ser neket. Hesab, destûr û sînorê kontrol bike.','Optionen oder Zuweisung fehlgeschlagen. Konto, Berechtigungen und Bereich prüfen.','Could not load options or assign the role. Check account, permission and scope.'],retry:['إعادة تحميل الخيارات','Vebijarkan nû bike','Optionen neu laden','Reload options']};
export function AdminScopedAssignment({lang}:{lang:Locale}){
 const t=(key:string)=>copy[key]?.[['ar','ku','de','en'].indexOf(lang)]??key;
 const [roles,setRoles]=useState<AdminRow[]>([]),[marketRows,setMarkets]=useState<Market[]>([]),[locations,setLocations]=useState<ActiveLocation[]>([]),[categories,setCategories]=useState<{id:string;names:Record<string,string>}[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[version,setVersion]=useState(0);
 const [email,setEmail]=useState(''),[role,setRole]=useState(''),[market,setMarket]=useState(''),[location,setLocation]=useState(''),[category,setCategory]=useState(''),[expiry,setExpiry]=useState(''),[note,setNote]=useState('');
 useEffect(()=>{let live=true;setLoading(true);setError(false);Promise.all([staffRoles(),markets(),activeLocations(),supabase.from('listing_categories_config').select('id,names').eq('is_active',true).order('sort_order')]).then(([r,m,l,c])=>{if(c.error)throw c.error;if(live){setRoles(r);setMarkets(m);setLocations(l);setCategories(c.data??[]);}}).catch(()=>{if(live)setError(true);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[version]);
 const field='mt-1 w-full rounded-xl border p-3';
 return <section className="space-y-3 rounded-3xl bg-white p-5"><h2 className="text-xl font-black">{t('title')}</h2><p className="text-sm text-gray-600">{t('note')}</p>{error&&<p role="alert" className="text-sm text-rojRed">{t('error')}</p>}{notice&&<p role="status">{notice}</p>}<form onSubmit={async e=>{e.preventDefault();if(busy||loading||!window.confirm(t('confirm')))return;setBusy(true);setError(false);setNotice('');try{await assignScopedStaff(email,role,{marketId:market,locationId:location?Number(location):null,categoryId:category,expiresAt:expiry?new Date(expiry).toISOString():null},note);setNotice(t('saved'));}catch{setError(true);}finally{setBusy(false);}}}><fieldset disabled={loading||busy} className="space-y-3"><div className="grid gap-3 md:grid-cols-2"><label>{t('email')}<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className={field}/></label><label>{t('role')}<select required value={role} onChange={e=>setRole(e.target.value)} className={field}><option value="">—</option>{roles.map(r=><option key={String(r.id)} value={String(r.role_key)}>{String((r.names as Record<string,string>)?.[lang]||(r.names as Record<string,string>)?.en||r.role_key)}</option>)}</select></label><label>{t('market')}<select value={market} onChange={e=>setMarket(e.target.value)} className={field}><option value="">{t('any')}</option>{marketRows.map(m=><option key={m.id} value={m.id}>{m.names[lang]||m.names.ar||m.code}</option>)}</select></label><label>{t('category')}<select value={category} onChange={e=>setCategory(e.target.value)} className={field}><option value="">{t('any')}</option>{categories.map(c=><option key={c.id} value={c.id}>{c.names[lang]||c.names.ar||c.id}</option>)}</select></label><label>{t('location')}<select value={location} onChange={e=>setLocation(e.target.value)} className={field}><option value="">{t('any')}</option>{locations.map(l=><option key={l.id} value={l.id}>{locationPath(locations,l.id,lang)||l.names[lang]||l.names.ar}</option>)}</select></label><label>{t('expiry')}<input type="datetime-local" value={expiry} onChange={e=>setExpiry(e.target.value)} className={field}/></label></div><label className="block">{t('reason')}<textarea value={note} onChange={e=>setNote(e.target.value)} className={field}/></label><button disabled={!role||!email||(!market&&!location&&!category&&!expiry)} className="rounded-xl bg-rojRed px-4 py-3 font-bold text-white disabled:opacity-50">{t('save')}</button></fieldset></form><button type="button" disabled={busy||loading} onClick={()=>setVersion(v=>v+1)} className="text-sm underline">{loading?'…':t('retry')}</button></section>;
}
