'use client';
import {useEffect,useState} from 'react';
import {supabase} from '@/lib/supabase';
import {staffRoles,type AdminRow} from '@/services/admin-operations';
import {activeAssignment,permissionLabel} from '@/lib/staff-display';
import {accountText} from '@/lib/account-copy';
import type {Locale} from '@/lib/i18n-config';
const copy={ar:{role:'دورك الحالي',tasks:'مهامك المسموحة',catalog:'الأدوار وصلاحياتها',scope:'قد تكون الصلاحيات مقيدة بالمنطقة أو القسم المحدد في التعيين. القرار النهائي لكل إجراء تطبّقه قاعدة البيانات.',owner:'مالك المنصة',unknown:'لا يوجد تعيين نشط ظاهر؛ الصلاحيات الفعلية موضحة أدناه.',empty:'لا توجد مهام مفعّلة.',rank:'الرتبة'},ku:{role:'Rola te',tasks:'Erkên destûrdayî',catalog:'Rol û destûr',scope:'Destûr dikarin bi herêm an kategoriyê ve girêdayî bin. Bingeha daneyan her çalakiyê kontrol dike.',owner:'Xwediyê platformê',unknown:'Tayînkirina çalak nayê dîtin; destûr li jêr in.',empty:'Erka çalak tune.',rank:'Rêz'},de:{role:'Deine Rolle',tasks:'Erlaubte Aufgaben',catalog:'Rollen und Berechtigungen',scope:'Berechtigungen können auf zugewiesene Regionen oder Kategorien beschränkt sein. Jede Aktion wird von der Datenbank geprüft.',owner:'Plattforminhaber',unknown:'Keine aktive Zuweisung sichtbar; aktuelle Berechtigungen stehen unten.',empty:'Keine Aufgaben aktiviert.',rank:'Rang'},en:{role:'Your role',tasks:'Allowed tasks',catalog:'Roles and permissions',scope:'Permissions may be restricted to assigned regions or categories. The database checks every action.',owner:'Platform owner',unknown:'No active assignment visible; current permissions are listed below.',empty:'No tasks enabled.',rank:'Rank'}};
export function StaffRoleGuide({lang,owner,permissions}:{lang:Locale;owner:boolean;permissions:Record<string,boolean>}){
 const t=copy[lang],[roles,setRoles]=useState<AdminRow[]>([]),[assigned,setAssigned]=useState<string[]>([]),[failed,setFailed]=useState(false),[version,setVersion]=useState(0);
 useEffect(()=>{let live=true;setFailed(false);void(async()=>{const {data,error}=await supabase.auth.getUser();if(error)throw error;if(!data.user)throw new Error('authentication_required');const [catalog,assignments]=await Promise.all([staffRoles(),supabase.from('staff_assignments').select('role_id,is_active,starts_at,expires_at').eq('user_id',data.user.id).eq('is_active',true)]);if(assignments.error)throw assignments.error;if(live){setRoles(catalog);setAssigned((assignments.data??[]).filter(a=>activeAssignment(a)).map(a=>String(a.role_id)));}})().catch(()=>{if(live)setFailed(true);});return()=>{live=false;};},[version]);
 const name=(r:AdminRow)=>String((r.names as Record<string,string>)?.[lang]||(r.names as Record<string,string>)?.en||r.role_key);
 const tasks=Object.entries(permissions).filter(([key,on])=>on&&key!=='assigned').map(([key])=>key);
 return <section className="space-y-3 rounded-2xl bg-white p-5"><h2 className="font-black">{t.role}</h2><p>{owner?t.owner:roles.filter(r=>assigned.includes(String(r.id))).map(name).join(' · ')||t.unknown}</p><h3 className="font-bold">{t.tasks}</h3><ul className="flex flex-wrap gap-2">{tasks.map(k=><li className="rounded-lg bg-rojWarmBg p-2 text-sm" key={k}>{permissionLabel(k,lang)}</li>)}</ul>{!tasks.length&&!owner&&<p>{t.empty}</p>}<p className="text-sm text-gray-600">{t.scope}</p>{failed?<p role="alert">{accountText(lang,'error')} <button className="font-bold text-rojRed" onClick={()=>setVersion(v=>v+1)}>{accountText(lang,'retry')}</button></p>:<details><summary className="cursor-pointer font-bold text-rojRed">{t.catalog}</summary><div className="mt-3 grid gap-3 md:grid-cols-2">{roles.map(r=><article key={String(r.id)} className="rounded-xl border p-3"><h3 className="font-bold">{name(r)}</h3><p className="text-xs text-gray-500">{t.rank}: {String(r.rank)}</p><ul className="mt-2 list-inside list-disc text-sm">{(Array.isArray(r.staff_role_permissions)?r.staff_role_permissions:[]).map((p:{permission_key:string})=><li key={p.permission_key}>{permissionLabel(p.permission_key,lang)}</li>)}</ul></article>)}</div></details>}</section>;
}
