'use client';
import {useCallback,useEffect,useState} from 'react';
import Image from 'next/image';
import {ownListingMedia,removeOwnListingMedia,type OwnMedia} from '@/services/listing-media';
import type {Locale} from '@/lib/i18n-config';
const copy={ar:{title:'الصور والفيديو المحفوظة',note:'الحذف هنا يطبق فوراً على الإعلان. الملفات الجديدة أدناه لا تُرفع إلا عند الحفظ.',remove:'حذف',confirm:'حذف هذا الملف المحفوظ من الإعلان الآن؟',retry:'تحديث الملفات',error:'تعذّر إتمام العملية. تحقق من الاتصال والصلاحية وأعد المحاولة.',empty:'لا توجد ملفات محفوظة.',image:'صورة الإعلان'},ku:{title:'Wêne û vîdyoyên tomarkirî',note:'Jêbirin yekser tê sepandin. Pelên nû yên li jêr bi tomarkirina formê tên barkirin.',remove:'Jê bibe',confirm:'Vê pelê niha ji îlanê jê bibî?',retry:'Pelan nû bike',error:'Çalakî bi ser neket. Girêdan û destûran kontrol bike û dîsa biceribîne.',empty:'Pela tomarkirî tune.',image:'Wêneya îlanê'},de:{title:'Gespeicherte Bilder und Videos',note:'Löschen wird sofort auf die Anzeige angewendet. Neue Dateien unten werden erst beim Speichern hochgeladen.',remove:'Löschen',confirm:'Diese gespeicherte Datei jetzt aus der Anzeige entfernen?',retry:'Dateien aktualisieren',error:'Vorgang fehlgeschlagen. Verbindung und Berechtigungen prüfen und erneut versuchen.',empty:'Keine gespeicherten Dateien.',image:'Anzeigenbild'},en:{title:'Saved images and videos',note:'Deletion applies to the listing immediately. New files below upload only when saving the form.',remove:'Delete',confirm:'Remove this saved file from the listing now?',retry:'Refresh files',error:'Operation failed. Check your connection and permissions and retry.',empty:'No saved files.',image:'Listing image'}};
export function ExistingListingMedia({id,lang,onBusy,onRemoved}:{id:string;lang:Locale;onBusy:(busy:boolean)=>void;onRemoved:(media:OwnMedia)=>void}){
 const t=copy[lang],[items,setItems]=useState<OwnMedia[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(false);
 const load=useCallback(async()=>{const rows=await ownListingMedia(id);setItems(rows);setError(false);},[id]);
 useEffect(()=>{let live=true;setLoading(true);ownListingMedia(id).then(rows=>{if(live){setItems(rows);setError(false);}}).catch(()=>{if(live)setError(true);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[id]);
 return <section className="space-y-3 rounded-2xl bg-white p-4"><h2 className="font-bold">{t.title}</h2><p className="text-sm text-gray-600">{t.note}</p>{loading?<p role="status">…</p>:<div className="grid gap-3 sm:grid-cols-3">{items.map(item=><article key={item.id} className="min-w-0 overflow-hidden rounded-xl border p-2">{item.kind==='image'?<Image unoptimized src={item.url} alt={t.image} width={320} height={240} className="h-36 w-full object-cover"/>:<video controls preload="metadata" src={item.url} className="h-36 w-full"/>}<button type="button" disabled={busy} className="mt-2 rounded-lg border px-3 py-2 text-sm text-rojRed" onClick={async()=>{if(busy||!window.confirm(t.confirm))return;setBusy(true);onBusy(true);setError(false);try{await removeOwnListingMedia(id,item.id);setItems(rows=>rows.filter(row=>row.id!==item.id));onRemoved(item);}catch{setError(true);}finally{setBusy(false);onBusy(false);}}}>{t.remove}</button></article>)}</div>}{!loading&&!error&&!items.length&&<p className="text-sm">{t.empty}</p>}{error&&<p role="alert" className="text-sm text-rojRed">{t.error}</p>}<button type="button" disabled={busy||loading} className="text-sm underline" onClick={()=>{setLoading(true);void load().catch(()=>setError(true)).finally(()=>setLoading(false));}}>{t.retry}</button></section>;
}
