'use client';
import {useEffect,useRef,useState} from 'react';
import type {Locale} from '@/lib/i18n-config';
type Coordinates={latitude:number|null;longitude:number|null};
const copy={ar:{title:'موقع الإعلان على الخريطة (اختياري)',note:'أضف موقع العقار أو الغرض، وليس موقعك الشخصي إن كان مختلفاً. قد تظهر الإحداثيات لزوار الإعلان. فتح الخريطة يرسل الموقع المحدد إلى OpenStreetMap.',locate:'استخدام موقعي الحالي',clear:'مسح الإحداثيات',lat:'خط العرض',lon:'خط الطول',map:'عرض النقطة على الخريطة',error:'تعذر تحديد الموقع. اسمح بالوصول إلى الموقع أو أدخل الإحداثيات يدوياً.',invalid:'أدخل الإحداثيين معاً ضمن المجال الصحيح.'},ku:{title:'Cihê îlanê li ser nexşeyê (bijartî)',note:'Cihê milk an tiştê binivîse, ne cihê xwe heke cuda be. Koordînat dikarin ji bo temaşevanan xuya bibin. Vekirina nexşeyê cihê dişîne OpenStreetMap.',locate:'Cihê min ê niha',clear:'Koordînatan paqij bike',lat:'Firehî',lon:'Dirêjî',map:'Xalê li ser nexşeyê bibîne',error:'Cih nehat dîtin. Destûra cihê bide an koordînatan binivîse.',invalid:'Her du koordînatan di sînorê rast de binivîse.'},de:{title:'Anzeigenstandort auf der Karte (optional)',note:'Standort des Objekts angeben, nicht deinen Aufenthaltsort, falls abweichend. Koordinaten können für Besucher sichtbar sein. Beim Öffnen der Karte wird der gewählte Standort an OpenStreetMap übermittelt.',locate:'Aktuellen Standort verwenden',clear:'Koordinaten entfernen',lat:'Breitengrad',lon:'Längengrad',map:'Punkt auf Karte ansehen',error:'Standort nicht verfügbar. Standortzugriff erlauben oder Koordinaten eingeben.',invalid:'Beide Koordinaten innerhalb des gültigen Bereichs eingeben.'},en:{title:'Listing map location (optional)',note:'Use the property or item location, not your personal location if different. Coordinates may be visible to listing visitors. Opening the map sends the selected location to OpenStreetMap.',locate:'Use my current location',clear:'Clear coordinates',lat:'Latitude',lon:'Longitude',map:'View point on map',error:'Location unavailable. Allow location access or enter coordinates manually.',invalid:'Enter both coordinates within the valid range.'}};
export function GeoLocationFields({lang,value,onChange,onBusy}:{lang:Locale;value:Coordinates;onChange:(value:Coordinates)=>void;onBusy:(busy:boolean)=>void}){
 const t=copy[lang],[busy,setBusy]=useState(false),[error,setError]=useState(false),request=useRef(0);
 useEffect(()=>()=>{request.current++;},[]);
 useEffect(()=>{onBusy(busy);return()=>onBusy(false);},[busy,onBusy]);
 const valid=value.latitude!==null&&value.longitude!==null&&Number.isFinite(value.latitude)&&Number.isFinite(value.longitude)&&Math.abs(value.latitude)<=90&&Math.abs(value.longitude)<=180;
 return <section className="space-y-3 rounded-2xl bg-white p-4"><h2 className="font-bold">{t.title}</h2><p className="text-sm text-gray-600">{t.note}</p><div className="flex flex-wrap gap-3"><button type="button" disabled={busy} className="rounded-xl border px-3 py-2 font-bold" onClick={()=>{const token=++request.current;setError(false);if(!navigator.geolocation){setError(true);return;}setBusy(true);navigator.geolocation.getCurrentPosition(position=>{if(token===request.current){onChange({latitude:Number(position.coords.latitude.toFixed(6)),longitude:Number(position.coords.longitude.toFixed(6))});setBusy(false);}},()=>{if(token===request.current){setError(true);setBusy(false);}},{enableHighAccuracy:false,timeout:10000,maximumAge:60000});}}>{busy?'…':t.locate}</button><button type="button" className="text-sm underline" onClick={()=>{request.current++;setBusy(false);setError(false);onChange({latitude:null,longitude:null});}}>{t.clear}</button></div><div className="grid gap-3 sm:grid-cols-2">{(['latitude','longitude']as const).map(key=><label key={key} className="text-sm font-bold">{key==='latitude'?t.lat:t.lon}<input disabled={busy} type="number" step="any" min={key==='latitude'?-90:-180} max={key==='latitude'?90:180} dir="ltr" value={value[key]??''} onChange={e=>onChange({...value,[key]:e.target.value===''?null:Number(e.target.value)})} className="mt-1 w-full rounded-xl border p-3"/></label>)}</div>{error&&<p role="alert" className="text-sm text-rojRed">{t.error}</p>}{!valid&&(value.latitude!==null||value.longitude!==null)&&<p role="alert" className="text-sm text-rojRed">{t.invalid}</p>}{valid&&<a href={`https://www.openstreetmap.org/?mlat=${value.latitude}&mlon=${value.longitude}#map=16/${value.latitude}/${value.longitude}`} target="_blank" rel="noopener noreferrer" className="inline-block text-sm text-rojRed underline">{t.map}</a>}</section>;
}
