'use client';
import {useState} from 'react';
import Link from 'next/link';
import {useAccount} from '@/components/account/useAccount';
import {reportContent,reportReasons,blockSeller} from '@/services/safety';
import {accountText} from '@/lib/account-copy';
import type {Locale} from '@/lib/i18n-config';
const copy={ar:{report:'الإبلاغ',listing:'عن الإعلان',user:'عن المعلن',details:'تفاصيل البلاغ',send:'إرسال البلاغ',done:'تم إرسال البلاغ للمراجعة.',duplicate:'لديك بلاغ مفتوح بالفعل عن هذا المحتوى.',block:'حظر المعلن',confirm:'حظر هذا المعلن؟ يمكنك إلغاء الحظر من حسابي.',blocked:'تم حظر المعلن.',reason:'سبب البلاغ'},ku:{report:'Rapor bike',listing:'Îlan',user:'Firoşkar',details:'Hûrgilî',send:'Raporê bişîne',done:'Rapor ji bo kontrolê hat şandin.',duplicate:'Rapora te ya vekirî heye.',block:'Firoşkar asteng bike',confirm:'Vî firoşkarî asteng bikî? Ji hesabê xwe dikarî astengê rakî.',blocked:'Firoşkar hat astengkirin.',reason:'Sedem'},de:{report:'Melden',listing:'Anzeige',user:'Anbieter',details:'Details zur Meldung',send:'Meldung senden',done:'Meldung zur Prüfung gesendet.',duplicate:'Du hast diesen Inhalt bereits gemeldet.',block:'Anbieter blockieren',confirm:'Diesen Anbieter blockieren? Du kannst die Blockierung im Konto aufheben.',blocked:'Anbieter blockiert.',reason:'Meldegrund'},en:{report:'Report',listing:'Listing',user:'Seller',details:'Report details',send:'Send report',done:'Report submitted for review.',duplicate:'You already have an open report for this content.',block:'Block seller',confirm:'Block this seller? You can unblock them from your account.',blocked:'Seller blocked.',reason:'Report reason'}};
const reasons:Record<string,string[]>={spam:['إزعاج','Spam','Spam','Spam'],fraud:['احتيال','Xapandin','Betrug','Fraud'],illegal:['محتوى مخالف','Naveroka neqanûnî','Unzulässiger Inhalt','Illegal content'],harassment:['مضايقة','Acizkirin','Belästigung','Harassment'],hate:['كراهية','Nefret','Hass','Hate'],sexual:['محتوى جنسي','Naveroka cinsî','Sexueller Inhalt','Sexual content'],violence:['عنف','Şîdet','Gewalt','Violence'],privacy:['انتهاك الخصوصية','Binpêkirina nepeniyê','Datenschutzverletzung','Privacy violation'],misleading:['معلومات مضللة','Agahiyên şaş','Irreführend','Misleading'],duplicate:['إعلان مكرر','Îlana dubare','Duplikat','Duplicate'],wrong_category:['قسم خاطئ','Beşa şaş','Falsche Kategorie','Wrong category'],other:['سبب آخر','Sedemeke din','Anderer Grund','Other']};
export function SafetyActions({lang,listingId,sellerId}:{lang:Locale;listingId:string;sellerId:string}){
 const auth=useAccount(),t=copy[lang],[open,setOpen]=useState(false),[target,setTarget]=useState<'listing'|'user'>('listing'),[reason,setReason]=useState<typeof reportReasons[number]>('misleading'),[details,setDetails]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 if(auth.user?.id===sellerId)return null;
 return <div className="space-y-3 border-t pt-4"><button className="text-sm font-bold text-rojRed" onClick={()=>setOpen(v=>!v)}>{t.report}</button>{open&&(auth.user?<form className="space-y-3" onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setNotice('');try{await reportContent(target,target==='listing'?listingId:sellerId,reason,details);setNotice(t.done);setOpen(false);setDetails('');}catch(e){setNotice(typeof e==='object'&&e&&'code'in e&&e.code==='23505'?t.duplicate:accountText(lang,'actionError'));}finally{setBusy(false);}}}><fieldset disabled={busy} className="space-y-3"><select aria-label={t.report} value={target} onChange={e=>setTarget(e.target.value as 'listing'|'user')} className="w-full rounded-xl border p-3"><option value="listing">{t.listing}</option><option value="user">{t.user}</option></select><select aria-label={t.reason} className="w-full rounded-xl border p-3" value={reason} onChange={e=>setReason(e.target.value as typeof reason)}>{reportReasons.map(r=><option key={r} value={r}>{reasons[r][['ar','ku','de','en'].indexOf(lang)]}</option>)}</select><textarea aria-label={t.details} placeholder={t.details} required={reason==='other'} minLength={reason==='other'?3:undefined} maxLength={3000} value={details} onChange={e=>setDetails(e.target.value)} className="w-full rounded-xl border p-3"/><button className="rounded-xl bg-rojRed px-4 py-3 font-bold text-white">{t.send}</button></fieldset></form>:<Link className="block text-rojRed" href={`/${lang}/auth?next=${encodeURIComponent(`/${lang}/listings/${listingId}`)}`}>{accountText(lang,'login')}</Link>)}{auth.user&&<button disabled={busy} className="block text-sm" onClick={async()=>{if(busy||!window.confirm(t.confirm))return;setBusy(true);try{await blockSeller(sellerId);setNotice(t.blocked);}catch{setNotice(accountText(lang,'actionError'));}finally{setBusy(false);}}}>{t.block}</button>}{notice&&<p role="status" className="text-sm">{notice}</p>}</div>;
}
